name: deploy
on:
  push:
    branches: [main]
    paths:
      - '**'
      - '!README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Package Registry
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build docker image
        run: docker build --build-arg REVISION_INFO="${GITHUB_SHA:0:7}-$(date +%Y%m%d_%H%M%S)" . -t markify

      - name: Tag and Push image
        run: |
          docker tag markify vdimir/markify:latest
          docker push vdimir/markify:latest

      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ubuntu
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_DEPLOY_PRIVATE_KEY }}"
          ssh -q $SSH_USER@$SSH_HOST "echo ok"

      - name: Deploy
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ubuntu
        run: |
          ssh $SSH_USER@$SSH_HOST "ansible-playbook --vault-password-file=.vault_pass -i inventory ansible/deploy.yml"
