name: test
on:
  push:
  pull_request:

jobs:
  gotest:
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go

    - name: Go get
      run: go get -v -t -d ./...

    - name: Test
      run: |
          go test -timeout=60s -covermode=count -coverprofile=$GITHUB_WORKSPACE/profile.cov ./...

    - name: Submit goveralls
      if: github.ref == 'refs/heads/main'
      run: |
        go get -u github.com/mattn/goveralls
        $(go env GOPATH)/bin/goveralls -service="github" -coverprofile=$GITHUB_WORKSPACE/profile.cov
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
