name: test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  gotest:
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Go get
      run: go get -v -t -d ./...

    - name: Go generate
      run: |
        go get github.com/rakyll/statik
        GOPATH=$(go env GOPATH) go generate ./...

    - name: Test
      run: |
          go test -timeout=60s -covermode=count -coverprofile=$GITHUB_WORKSPACE/profile.cov ./...

    - name: Submit goveralls
      run: |
        mv $GITHUB_WORKSPACE/profile.cov $GITHUB_WORKSPACE/profile.cov_tmp
        grep -v "statik.go:" $GITHUB_WORKSPACE/profile.cov_tmp > $GITHUB_WORKSPACE/profile.cov
        go get -u github.com/mattn/goveralls
        $(go env GOPATH)/bin/goveralls -service="github" -coverprofile=$GITHUB_WORKSPACE/profile.cov
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
